# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/lib/python3.12/dist-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /usr/local/lib/python3.12/dist-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /disc/apdcephfs_nj7/share_302776988/rainyxsong/rain-ops

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /disc/apdcephfs_nj7/share_302776988/rainyxsong/rain-ops

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/local/lib/python3.12/dist-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/lib/python3.12/dist-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /disc/apdcephfs_nj7/share_302776988/rainyxsong/rain-ops/CMakeFiles /disc/apdcephfs_nj7/share_302776988/rainyxsong/rain-ops//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /disc/apdcephfs_nj7/share_302776988/rainyxsong/rain-ops/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named matmul.out

# Build rule for target.
matmul.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 matmul.out
.PHONY : matmul.out

# fast build rule for target.
matmul.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/build
.PHONY : matmul.out/fast

matmul/baseline.o: matmul/baseline.cu.o
.PHONY : matmul/baseline.o

# target to build an object file
matmul/baseline.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/baseline.cu.o
.PHONY : matmul/baseline.cu.o

matmul/baseline.i: matmul/baseline.cu.i
.PHONY : matmul/baseline.i

# target to preprocess a source file
matmul/baseline.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/baseline.cu.i
.PHONY : matmul/baseline.cu.i

matmul/baseline.s: matmul/baseline.cu.s
.PHONY : matmul/baseline.s

# target to generate assembly for a file
matmul/baseline.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/baseline.cu.s
.PHONY : matmul/baseline.cu.s

matmul/common.o: matmul/common.cu.o
.PHONY : matmul/common.o

# target to build an object file
matmul/common.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/common.cu.o
.PHONY : matmul/common.cu.o

matmul/common.i: matmul/common.cu.i
.PHONY : matmul/common.i

# target to preprocess a source file
matmul/common.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/common.cu.i
.PHONY : matmul/common.cu.i

matmul/common.s: matmul/common.cu.s
.PHONY : matmul/common.s

# target to generate assembly for a file
matmul/common.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/common.cu.s
.PHONY : matmul/common.cu.s

matmul/main.o: matmul/main.cu.o
.PHONY : matmul/main.o

# target to build an object file
matmul/main.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/main.cu.o
.PHONY : matmul/main.cu.o

matmul/main.i: matmul/main.cu.i
.PHONY : matmul/main.i

# target to preprocess a source file
matmul/main.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/main.cu.i
.PHONY : matmul/main.cu.i

matmul/main.s: matmul/main.cu.s
.PHONY : matmul/main.s

# target to generate assembly for a file
matmul/main.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/main.cu.s
.PHONY : matmul/main.cu.s

matmul/manager.o: matmul/manager.cu.o
.PHONY : matmul/manager.o

# target to build an object file
matmul/manager.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/manager.cu.o
.PHONY : matmul/manager.cu.o

matmul/manager.i: matmul/manager.cu.i
.PHONY : matmul/manager.i

# target to preprocess a source file
matmul/manager.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/manager.cu.i
.PHONY : matmul/manager.cu.i

matmul/manager.s: matmul/manager.cu.s
.PHONY : matmul/manager.s

# target to generate assembly for a file
matmul/manager.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/manager.cu.s
.PHONY : matmul/manager.cu.s

matmul/mm.o: matmul/mm.cu.o
.PHONY : matmul/mm.o

# target to build an object file
matmul/mm.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/mm.cu.o
.PHONY : matmul/mm.cu.o

matmul/mm.i: matmul/mm.cu.i
.PHONY : matmul/mm.i

# target to preprocess a source file
matmul/mm.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/mm.cu.i
.PHONY : matmul/mm.cu.i

matmul/mm.s: matmul/mm.cu.s
.PHONY : matmul/mm.s

# target to generate assembly for a file
matmul/mm.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/mm.cu.s
.PHONY : matmul/mm.cu.s

matmul/mm_v1.o: matmul/mm_v1.cu.o
.PHONY : matmul/mm_v1.o

# target to build an object file
matmul/mm_v1.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/mm_v1.cu.o
.PHONY : matmul/mm_v1.cu.o

matmul/mm_v1.i: matmul/mm_v1.cu.i
.PHONY : matmul/mm_v1.i

# target to preprocess a source file
matmul/mm_v1.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/mm_v1.cu.i
.PHONY : matmul/mm_v1.cu.i

matmul/mm_v1.s: matmul/mm_v1.cu.s
.PHONY : matmul/mm_v1.s

# target to generate assembly for a file
matmul/mm_v1.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/mm_v1.cu.s
.PHONY : matmul/mm_v1.cu.s

matmul/mm_v2.o: matmul/mm_v2.cu.o
.PHONY : matmul/mm_v2.o

# target to build an object file
matmul/mm_v2.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/mm_v2.cu.o
.PHONY : matmul/mm_v2.cu.o

matmul/mm_v2.i: matmul/mm_v2.cu.i
.PHONY : matmul/mm_v2.i

# target to preprocess a source file
matmul/mm_v2.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/mm_v2.cu.i
.PHONY : matmul/mm_v2.cu.i

matmul/mm_v2.s: matmul/mm_v2.cu.s
.PHONY : matmul/mm_v2.s

# target to generate assembly for a file
matmul/mm_v2.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/mm_v2.cu.s
.PHONY : matmul/mm_v2.cu.s

matmul/mm_v3.o: matmul/mm_v3.cu.o
.PHONY : matmul/mm_v3.o

# target to build an object file
matmul/mm_v3.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/mm_v3.cu.o
.PHONY : matmul/mm_v3.cu.o

matmul/mm_v3.i: matmul/mm_v3.cu.i
.PHONY : matmul/mm_v3.i

# target to preprocess a source file
matmul/mm_v3.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/mm_v3.cu.i
.PHONY : matmul/mm_v3.cu.i

matmul/mm_v3.s: matmul/mm_v3.cu.s
.PHONY : matmul/mm_v3.s

# target to generate assembly for a file
matmul/mm_v3.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/mm_v3.cu.s
.PHONY : matmul/mm_v3.cu.s

matmul/mm_v4.o: matmul/mm_v4.cu.o
.PHONY : matmul/mm_v4.o

# target to build an object file
matmul/mm_v4.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/mm_v4.cu.o
.PHONY : matmul/mm_v4.cu.o

matmul/mm_v4.i: matmul/mm_v4.cu.i
.PHONY : matmul/mm_v4.i

# target to preprocess a source file
matmul/mm_v4.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/mm_v4.cu.i
.PHONY : matmul/mm_v4.cu.i

matmul/mm_v4.s: matmul/mm_v4.cu.s
.PHONY : matmul/mm_v4.s

# target to generate assembly for a file
matmul/mm_v4.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/mm_v4.cu.s
.PHONY : matmul/mm_v4.cu.s

matmul/mm_v5.o: matmul/mm_v5.cu.o
.PHONY : matmul/mm_v5.o

# target to build an object file
matmul/mm_v5.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/mm_v5.cu.o
.PHONY : matmul/mm_v5.cu.o

matmul/mm_v5.i: matmul/mm_v5.cu.i
.PHONY : matmul/mm_v5.i

# target to preprocess a source file
matmul/mm_v5.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/mm_v5.cu.i
.PHONY : matmul/mm_v5.cu.i

matmul/mm_v5.s: matmul/mm_v5.cu.s
.PHONY : matmul/mm_v5.s

# target to generate assembly for a file
matmul/mm_v5.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/mm_v5.cu.s
.PHONY : matmul/mm_v5.cu.s

matmul/mm_v6.o: matmul/mm_v6.cu.o
.PHONY : matmul/mm_v6.o

# target to build an object file
matmul/mm_v6.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/mm_v6.cu.o
.PHONY : matmul/mm_v6.cu.o

matmul/mm_v6.i: matmul/mm_v6.cu.i
.PHONY : matmul/mm_v6.i

# target to preprocess a source file
matmul/mm_v6.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/mm_v6.cu.i
.PHONY : matmul/mm_v6.cu.i

matmul/mm_v6.s: matmul/mm_v6.cu.s
.PHONY : matmul/mm_v6.s

# target to generate assembly for a file
matmul/mm_v6.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/mm_v6.cu.s
.PHONY : matmul/mm_v6.cu.s

matmul/mm_v7.o: matmul/mm_v7.cu.o
.PHONY : matmul/mm_v7.o

# target to build an object file
matmul/mm_v7.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/mm_v7.cu.o
.PHONY : matmul/mm_v7.cu.o

matmul/mm_v7.i: matmul/mm_v7.cu.i
.PHONY : matmul/mm_v7.i

# target to preprocess a source file
matmul/mm_v7.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/mm_v7.cu.i
.PHONY : matmul/mm_v7.cu.i

matmul/mm_v7.s: matmul/mm_v7.cu.s
.PHONY : matmul/mm_v7.s

# target to generate assembly for a file
matmul/mm_v7.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/mm_v7.cu.s
.PHONY : matmul/mm_v7.cu.s

matmul/timer.o: matmul/timer.cu.o
.PHONY : matmul/timer.o

# target to build an object file
matmul/timer.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/timer.cu.o
.PHONY : matmul/timer.cu.o

matmul/timer.i: matmul/timer.cu.i
.PHONY : matmul/timer.i

# target to preprocess a source file
matmul/timer.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/timer.cu.i
.PHONY : matmul/timer.cu.i

matmul/timer.s: matmul/timer.cu.s
.PHONY : matmul/timer.s

# target to generate assembly for a file
matmul/timer.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matmul.out.dir/build.make CMakeFiles/matmul.out.dir/matmul/timer.cu.s
.PHONY : matmul/timer.cu.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... matmul.out"
	@echo "... matmul/baseline.o"
	@echo "... matmul/baseline.i"
	@echo "... matmul/baseline.s"
	@echo "... matmul/common.o"
	@echo "... matmul/common.i"
	@echo "... matmul/common.s"
	@echo "... matmul/main.o"
	@echo "... matmul/main.i"
	@echo "... matmul/main.s"
	@echo "... matmul/manager.o"
	@echo "... matmul/manager.i"
	@echo "... matmul/manager.s"
	@echo "... matmul/mm.o"
	@echo "... matmul/mm.i"
	@echo "... matmul/mm.s"
	@echo "... matmul/mm_v1.o"
	@echo "... matmul/mm_v1.i"
	@echo "... matmul/mm_v1.s"
	@echo "... matmul/mm_v2.o"
	@echo "... matmul/mm_v2.i"
	@echo "... matmul/mm_v2.s"
	@echo "... matmul/mm_v3.o"
	@echo "... matmul/mm_v3.i"
	@echo "... matmul/mm_v3.s"
	@echo "... matmul/mm_v4.o"
	@echo "... matmul/mm_v4.i"
	@echo "... matmul/mm_v4.s"
	@echo "... matmul/mm_v5.o"
	@echo "... matmul/mm_v5.i"
	@echo "... matmul/mm_v5.s"
	@echo "... matmul/mm_v6.o"
	@echo "... matmul/mm_v6.i"
	@echo "... matmul/mm_v6.s"
	@echo "... matmul/mm_v7.o"
	@echo "... matmul/mm_v7.i"
	@echo "... matmul/mm_v7.s"
	@echo "... matmul/timer.o"
	@echo "... matmul/timer.i"
	@echo "... matmul/timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

